from .lvl1 import Level1
from .lvl2 import Level2
from .lvl3 import Level3
from .lvl4 import Level4
from .lvl5 import Level5
from .lvl6 import Level6
from .lvl7 import Level7
from .lvl8 import Level8
from .lvl9 import Level9
